remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Red Hat Community Termine
description: Hier findest du die österreichischen Red Hat Community Termine
show_downloads:  true
