theme = 'npq-hugo'
baseURL = "https://test1-rh-events-at.apps.ocp4.openshift.freeddns.org/"
languageCode = "en-us"
title = "Events Austria"
copyright = "Deployed with ❤️ on OpenShift"
pygmentsUseClasses=true

[params]
  author = "Mahmuthan Bastug"
  description = "your description"
  keywords = "hugo blog"
  useAvatar = true
  microBlogSection = "posts"
  displayMicroBlog = false
  displayRecent = false
  recentMax = 4
  mail = "david.hanacek@redhat.com"
  formspreeID = "yourformspreeID"

[menu]
  [[menu.main]]
    name = "Events"
    pre = "<i class=\"fas fa-calendar fa-sm\"></i>"
    url = "/"
    weight = -9 
  [[menu.main]]
    name = "Red Hat Team"
    pre = "<i class=\"fas fa-tags fa-ms\"></i>"
    url = "/about/"
    weight = -8 