theme = 'npq-hugo'
baseURL = "/"
languageCode = "en-us"
title = "RH Events Austria"
copyright = "Deployed with ❤️ on OpenShift"
pygmentsUseClasses=true

[params]
  author = "Shadowman"
  description = "overview of all events of redhat austria"
  keywords = "redhat austria events"
  useAvatar = true
  microBlogSection = "posts"
  displayMicroBlog = false
  displayHomeContent = true
  displayRecent = false
  recentMax = 4
  mail = "david.hanacek@redhat.com"

[menu]
  [[menu.main]]
    name = "Events"
    pre = "<i class=\"fas fa-calendar fa-sm\"></i>"
    url = "/"
    weight = -9 
  [[menu.main]]
    name = "Red Hat Team"
    pre = "<i class=\"fas fa-address-book fa-ms\"></i>"
    url = "/team/"
    weight = -8 
